<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@3.0.3 static/models/not-the-louvre-studio.glb --transform --types --isolated --keepnames --root /models/ --output src/lib/features/home-entry-scene/scene/NotTheLouvreStudioModel.svelte
-->

<script lang="ts">
	import type * as THREE from 'three';

	import type { Snippet } from 'svelte';
	import { T } from '@threlte/core';
	import { useDraco, useGltf } from '@threlte/extras';

	type GLTFResult = {
		nodes: {
			Cone_abajur_0: THREE.Mesh;
			Cube001_koyumavi_0: THREE.Mesh;
			Cube009_tahta_0: THREE.Mesh;
			Cube022_perde_0: THREE.Mesh;
			Cube023_cam_0: THREE.Mesh;
			Cube023_pencere_0: THREE.Mesh;
			Plane_zemin_0: THREE.Mesh;
			Plane001_duvar_0: THREE.Mesh;
		};
		materials: {
			PaletteMaterial001: THREE.MeshStandardMaterial;
			PaletteMaterial002: THREE.MeshStandardMaterial;
			PaletteMaterial003: THREE.MeshStandardMaterial;
			PaletteMaterial004: THREE.MeshStandardMaterial;
			PaletteMaterial005: THREE.MeshStandardMaterial;
			PaletteMaterial006: THREE.MeshStandardMaterial;
			zemin: THREE.MeshStandardMaterial;
			PaletteMaterial007: THREE.MeshStandardMaterial;
		};
	};

	let {
		fallback,
		error,
		children,
		castShadow = true,
		receiveShadow = true,
		onload,
		onerror
	}: {
		children?: Snippet;
		fallback?: Snippet;
		error?: Snippet<[{ error: Error }]>;
		castShadow?: boolean;
		receiveShadow?: boolean;
		onload?: () => void;
		onerror?: (error: Error) => void;
	} = $props();

	const gltf = useGltf<GLTFResult>('/models/not-the-louvre-studio-transformed.glb', {
		dracoLoader: useDraco()
	});

	const model = gltf
		.then((result) => {
			onload?.();
			return result;
		})
		.catch((cause: unknown) => {
			const loadError =
				cause instanceof Error ? cause : new Error('Failed to load not-the-louvre studio model.');
			onerror?.(loadError);
			throw loadError;
		});
</script>

<T.Group dispose={false}>
	{#await model}
		{@render fallback?.()}
	{:then gltf}
		<T.Mesh
			{castShadow}
			name="Cone_abajur_0"
			geometry={gltf.nodes.Cone_abajur_0.geometry}
			material={gltf.materials.PaletteMaterial001}
			position={[-1.61, 0.96, -1.55]}
			{receiveShadow}
			rotation={[-Math.PI / 2, 0, 0]}
			scale={0.17}
		/>
		<T.Mesh
			{castShadow}
			name="Cube001_koyumavi_0"
			geometry={gltf.nodes.Cube001_koyumavi_0.geometry}
			material={gltf.materials.PaletteMaterial002}
			position={[1.51, 0.12, -1.66]}
			{receiveShadow}
			rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
			scale={0.18}
		/>
		<T.Mesh
			{castShadow}
			name="Cube009_tahta_0"
			geometry={gltf.nodes.Cube009_tahta_0.geometry}
			material={gltf.materials.PaletteMaterial003}
			position={[0.12, 0, 0.02]}
			{receiveShadow}
			rotation={[-Math.PI / 2, 0, -0.81]}
			scale={[0.43, 0.43, 0.48]}
		/>
		<T.Mesh
			{castShadow}
			name="Cube022_perde_0"
			geometry={gltf.nodes.Cube022_perde_0.geometry}
			material={gltf.materials.PaletteMaterial004}
			position={[-1.74, 1.92, 0.97]}
			{receiveShadow}
			rotation={[-Math.PI / 2, 0, 0]}
			scale={21.34}
		/>
		<T.Mesh
			{castShadow}
			name="Cube023_cam_0"
			geometry={gltf.nodes.Cube023_cam_0.geometry}
			material={gltf.materials.PaletteMaterial005}
			position={[-1.82, 0.47, 0]}
			{receiveShadow}
			rotation={[-Math.PI / 2, 0, Math.PI]}
			scale={[-0.32, 0.32, 0.32]}
		/>
		<T.Mesh
			{castShadow}
			name="Cube023_pencere_0"
			geometry={gltf.nodes.Cube023_pencere_0.geometry}
			material={gltf.materials.PaletteMaterial006}
			position={[-1.82, 0.47, 0]}
			{receiveShadow}
			rotation={[-Math.PI / 2, 0, Math.PI]}
			scale={[-0.32, 0.32, 0.32]}
		/>
		<T.Mesh
			{castShadow}
			name="Plane_zemin_0"
			geometry={gltf.nodes.Plane_zemin_0.geometry}
			material={gltf.materials.zemin}
			{receiveShadow}
			rotation={[-Math.PI / 2, 0, 0]}
			scale={1.84}
		/>
		<T.Mesh
			{castShadow}
			name="Plane001_duvar_0"
			geometry={gltf.nodes.Plane001_duvar_0.geometry}
			material={gltf.materials.PaletteMaterial007}
			{receiveShadow}
			rotation={[-Math.PI / 2, 0, 0]}
			scale={1.84}
		/>
	{:catch err}
		{@render error?.({ error: err })}
	{/await}

	{@render children?.()}
</T.Group>
